### ISSUE TITLE
What is the difference between yours and the author's code

### ISSUE THREAD

**Issue by feynman233** [dragen1860/LearningToCompare-Pytorch#10]
Hi, thanks for  your code!
      I wonder what is the difference between yours and the author's code https://github.com/floodsung/LearningToCompare_FSL

      It seems that you use the resnet as the basic network？
      Thanks a lot！

**Comment by dragen1860** [comment]
The author's code remove "deep model", which is exactly what mine offered. You can refer to author's previous version of arxiv paper to have a glimpse of what does `deep model` mean.
