### ISSUE TITLE
multi-gpu not considered in accuracy

### ISSUE THREAD

**Issue by fguney** [dragen1860/LearningToCompare-Pytorch#2]
in train.py, this only adds the sum of correct ones from GPU 0:
`total_correct += correct.data[0]`

it should be something like that in case of multiple GPUs, right?:

`for d in range(len(device_ids)):
        total_correct += correct.data[d]`

**Comment by dragen1860** [comment]
hi, yes, you are right. To be concise, you just need `total_correct += correct.sum()`.
