### ISSUE TITLE
exact details for the tables

### ISSUE THREAD

**Issue by fguney** [dragen1860/LearningToCompare-Pytorch#3]
It'd be great if you could share how you set the k_query and batcsz for the tables. 
Also, is it possible to share MiniImagenet dataset? I cannot find it online.

**Comment by dragen1860** [comment]
Hi, k_query is the query number of images per class, and it's not vital for performance, just set it to 1~5. To get more precise accuracy, you can set it to 15 in testing. set `batchsz`  as large as possible only if your GPU doesn't throw `out of cuda memory error`. 
for miniimagnet dataset, pls leave your email.

**Comment by buaa-luzhi** [comment]
@dragen1860 
Hello,  thanks for your contribution.
I also urgently need a MiniImagenet dataset. Can you send me a copy?
Thanks so much.
My email address is 108009413@qq.com
