### ISSUE TITLE
Access the miniImageNet dataset

### ISSUE THREAD

**Issue by zhangguanghui1** [dragen1860/LearningToCompare-Pytorch#4]
I try to download mini-Imagenet Dataset, but I cannot find it online. Can you share the link to the miniImageNet images?Thanks. zhanggh@mail.sim.ac.cn

**Comment by dragen1860** [comment]
Hi, please download from here: https://drive.google.com/open?id=1HkgrkAwukzEZA0TpO7010PkAOREb2Nuk

**Comment by zhangguanghui1** [comment]
Always download failed from Google Drive. Is there any other way to get the mini-Imagenet Dataset? Thanks a lot!

**Comment by zhangguanghui1** [comment]
Alaways failed to download it from Google Drive. Is there any other way to get the mini-Imagenet Dataset? Thanks a lot!

**Comment by dragen1860** [comment]
https://www.dropbox.com/s/ed1s1dgei9kxd2p/mini-imagenet.zip?dl=0

**Comment by zhangguanghui1** [comment]
Thank you very much!

**Comment by KaminLee** [comment]
I failed to download it from dropbox, too. Is there any other way to get the mini-Imagenet Dataset?

**Comment by wkzsgxxn** [comment]
I can't use the two links you shared. Do you have any other paths to get the data set? Thank you

**Comment by yangt1013** [comment]
Hi,I tried to reproduce your code, but I have a problem here
Traceback (most recent call last):
  File "/home/ty/MAML/miniimagenet_train.py", line 111, in <module>
    main()
  File "/home/ty/MAML/miniimagenet_train.py", line 60, in main
    batchsz=10000, resize=args.imgsz)
  File "/home/ty/MAML/MiniImagenet.py", line 65, in __init__
    csvdata = self.loadCSV(os.path.join(root, mode + '.csv'))  # csv path
  File "/home/ty/MAML/MiniImagenet.py", line 82, in loadCSV
    with open(csvf) as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: 'home/ty/MAML/miniimagenet/train.csv'

I checked the path and file without problems, I would like to ask how you solved it

**Comment by yangt1013** [comment]
The files name root-miniimagenet(includes image)-.csv ，is it  all right?

**Comment by silver-hzh** [comment]
> 
> 
> Hi,I tried to reproduce your code, but I have a problem here
> Traceback (most recent call last):
> File "/home/ty/MAML/miniimagenet_train.py", line 111, in
> main()
> File "/home/ty/MAML/miniimagenet_train.py", line 60, in main
> batchsz=10000, resize=args.imgsz)
> File "/home/ty/MAML/MiniImagenet.py", line 65, in **init**
> csvdata = self.loadCSV(os.path.join(root, mode + '.csv')) # csv path
> File "/home/ty/MAML/MiniImagenet.py", line 82, in loadCSV
> with open(csvf) as csvfile:
> FileNotFoundError: [Errno 2] No such file or directory: 'home/ty/MAML/miniimagenet/train.csv'
> 
> I checked the path and file without problems, I would like to ask how you solved it
I miss the same problem. I  delete '/'  in the code : mini = MiniImagenet('/home/i/tmp/MAML-Pytorch/miniimagenet', mode='train', n_way=args.n_way, k_shot=args.k_spt,
                        k_query=args.k_qry,
                        batchsz=10000, resize=args.imgsz)
After that it can be run

**Comment by silver-hzh** [comment]
i missed the same problem  and i delete a symbol in  code :     mini = MiniImagenet('/home/i/tmp/MAML-Pytorch/miniimagenet', mode='train', n_way=args.n_way, k_shot=args.k_spt,
                        k_query=args.k_qry,
                        batchsz=10000, resize=args.imgsz)
    mini_test = MiniImagenet('/home/i/tmp/MAML-Pytorch/miniimagenet', mode='test', n_way=args.n_way, k_shot=args.k_spt,
                             k_query=args.k_qry,
                             batchsz=100, resize=args.imgsz)
After that it can be run
