### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by 22wei22** [dragen1860/LearningToCompare-Pytorch#5]
As for the 5-way 1-shot experiments，in the paper,there are 19 * 5 + 1 * 5 = 100 images. I think  19 * 5 + 1 * 19 = 114 images. I can not understand it

**Comment by dragen1860** [comment]
every class includes 1 shot , namely 1 image, and 19 images for query. That's, 20 images for one category.
so 20 *5 = 100
